module.exports = {
S06E22 : {
  "playerData": [
    {
      "player": "Nik B",
      "charname": "Pitbull",
      "number": "41662",
      "charnumber": "7",
      "faction": "DkAr",
      "tier": "2",
      "pp": "2",
      "xp": "1",
      "gp": "1900",
      "dj": "5",
	  "crossouts" : "[1,2,3,4]"
    },
    {
      "charname": "Skarn",
      "player": "Cyril C",
      "gp": "1900",
      "xp": "1",
      "pp": "2",
      "tier": "2",
      "number": "76446",
      "charnumber": "15",
      "dj": "50",
      "faction": "DkAr",
	  "crossouts" : "[1,2]"
    },
    {
      "charname": "Bones",
      "player": "Glenn H",
      "gp": "1900",
      "xp": "1",
      "pp": "2",
      "tier": "2",
      "number": "11016",
      "charnumber": "2",
      "faction": "ScSg",
      "dj": "1",
	  "crossouts" : "[0,1,2]"

    },
    {
      "charname": "Rhanloi",
      "player": "Andy G",
      "gp": "1900",
      "xp": "1",
      "pp": "2",
      "tier": "2",
      "number": "83583",
      "charnumber": "1",
      "dj": "50",
      "faction": "SiCr",
	  "crossouts" : "[0,1,2]"
    },
    {
      "charname": "Boram",
      "player": "Pedwiddle",
      "gp": "1900",
      "xp": "1",
      "pp": "2",
      "tier": "2",
      "number": "70085",
      "charnumber": "2",
      "faction": "DkAr",
      "dj": "100",
	  "crossouts" : "[1,2]"
    },
    {
      "charname": "Rasamoro",
      "player": "Tiaburn",
      "gp": "1900",
      "xp": "1",
      "pp": "2",
      "tier": "2",
      "number": "34327",
      "charnumber": "10",
      "faction": "DkAr",
      "dj": "0",
	  "crossouts" : "[1,2]"
    }
  ],
  "gameName": "YSK622",
  "eventcode": "36581",
  "gmsig": "DMK",
  "scenario": "S06E22",
  "eventname": "DMK PbP",
  "date": "01/09/2015",
  "gmpfs": "108716"
},
S06E23 : {
  "playerData": [
    {
      "player": "Nik B",
      "charname": "Svetlana",
      "number": "41662",
      "charnumber": "4",
      "faction": "DkAr",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "4492",
      "dj": "75",
	  "crossouts" : "[1,2,3,4]"
    },
    {
      "charname": "Ourboreia",
      "player": "Cyril C",
      "gp": "4492",
      "xp": "1",
      "pp": "2",
      "tier": "0",
      "number": "76446",
      "charnumber": "4",
      "dj": "20",
      "faction": "ScSg",
	  "crossouts" : "[2,3,4]"
    },
    {
      "charname": "Ceobryrn",
      "player": "Glenn H",
      "gp": "4492",
      "xp": "1",
      "pp": "2",
      "tier": "1",
      "number": "11016",
      "charnumber": "1",
      "faction": "SvCt",
      "dj": "20",
	  "crossouts" : "[1,3,4]"
    },
    {
      "charname": "(Andys PG)",
      "player": "Andy G",
      "gp": "6117",
      "xp": "1",
      "pp": "2",
      "tier": "0",
      "number": "83583",
      "charnumber": "1",
      "dj": "X",
      "faction": "SiCr",
	  "crossouts" : "[1,2,3,4]"
    },
    {
      "charname": "Elindriel",
      "player": "Pedwiddle",
      "gp": "4492",
      "xp": "1",
      "pp": "2",
      "tier": "0",
      "number": "70085",
      "charnumber": "1",
      "faction": "SvCt",
      "dj": "75",
	  "crossouts" : "[1,3,4]"
    },
    {
      "charname": "(Karrions PG)",
      "player": "Cacumattus",
      "gp": "4492",
      "xp": "1",
      "pp": "2",
      "tier": "0",
      "number": "125832",
      "charnumber": "1",
      "faction": "GL",
      "dj": "X",
	  "crossouts" : "[1,2,3,4]"
    }
  ],
  "gameName": "YSK623",
  "eventcode": "36581",
  "gmsig": "DMK",
  "scenario": "S06E23",
  "eventname": "DMK PbP",
  "date": "01/09/2015",
  "gmpfs": "108716"
},
S06E98II : {
  "playerData": [
    {
      "player": "Luke Parry",
      "charname": "Howard P Lovecraft",
      "number": "2847",
      "charnumber": "41",
      "faction": "SiCr",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "4000",
      "dj": "X",
      "crossouts": "[0,1,2,4,5]"
    },
    {
      "charname": "Ka'zaak",
      "number": "75655",
      "charnumber": "9",
      "faction": "LbEd",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "4000",
      "dj": "X",
      "player": "TheBobJones",
      "crossouts": "[0,1,3,4,5]"
    },
    {
      "charname": "Clandelve Hammerhand",
      "number": "132076",
      "player": "PatheticWretch",
      "faction": "Exch",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "4000",
      "dj": "X",
      "crossouts": "[0,1,2,3,4]"
    },
    {
      "player": "Gerald",
      "charname": "Shel Whispertongue",
      "number": "12445",
      "charnumber": "3",
      "faction": "SvCt",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "4000",
      "dj": "X",
      "crossouts": "[1,2,3,4,5]"
    },
    {
      "player": "Zoomba",
      "charname": "Reginal Voorius III",
      "number": "127063",
      "charnumber": "8",
      "faction": "Exch",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "4000",
      "dj": "X",
      "crossouts": "[0,1,2,3,5]"
    }
  ],
  "gameName": "S698II",
  "eventname": "DMK PbP",
  "scenario": "S06E98",
  "eventcode": "36581",
  "date": "7/9/2015",
  "gmsig": "DMK",
  "gmpfs": "108716"
} ,
"S06E22II" :{
  "playerData": [
    {
      "player": "SirPeter",
      "charname": "Turak Kavendarth",
      "number": "113139",
      "charnumber": "1",
      "faction": "GL",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "510",
      "dj": "0",
      "comment": "DMK: Rolled > 15 on int check to forgo downtime",
      "crossouts": "[0,1,2,4]"
    },
    {
      "charname": "Seinary Kage",
      "number": "124236",
      "charnumber": "5",
      "faction": "GL",
      "tier": "1",
      "pp": "2",
      "xp": "1",
      "gp": "1205",
      "dj": "X",
      "player": "Alan Paron",
      "crossouts": "[0,1,2,4]"
    },
    {
      "charname": "Ella Fiddlepocket",
      "number": "44004",
      "player": "Tyler Beck",
      "faction": "GL",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "510",
      "dj": "X",
      "crossouts": "[0,1,2,4]",
      "charnumber": "23"
    },
    {
      "player": "Jasonrodarte520",
      "charname": "Bennybeck",
      "number": "43330",
      "charnumber": "1",
      "faction": "SiCr",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "510",
      "dj": "X",
      "crossouts": "[0,1,2,4]"
    },
    {
      "player": "Brad Elridge",
      "charname": "Bastian Thrune",
      "number": "184842",
      "charnumber": "2",
      "faction": "SiCr",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "510",
      "dj": "5",
      "crossouts": "[0,1,2,4]"
    },
    {
      "player": "Mike McKeown",
      "charname": "Siival Skyreaper",
      "number": "2072",
      "charnumber": "25",
      "faction": "SiCr",
      "tier": "0",
      "pp": "2",
      "xp": "1",
      "gp": "510",
      "dj": "X",
      "crossouts": "[0,1,2,4]"
    }
  ],
  "gameName": "S622II",
  "eventname": "DMK PbP",
  "scenario": "S06E22",
  "eventcode": "36581",
  "date": "10/9/2015",
  "gmsig": "DMK",
  "gmpfs": "108716"
} 

}